---
- name: "Create redis systemd unit file"
  template:
    src: redis.service.j2
    dest: "{{redis_systemd_unit_file}}"
    mode: 0644
    owner: "root"
    group: "root"
  notify: Restart redis

- name: "Start/enable redis"
  systemd:
    name: "{{redis_service}}"
    state: started
    enabled: yes

