---
ntp_package: "chrony"
ntp_service: "chronyd"
epel_repo_rpm: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm"
certbot_package: "certbot"
python_app_deps:
  - gcc
  - python-virtualenv
  - python-devel
app_server: "uwsgi"
app_server_config: "/etc/uwsgi.d/yardsale.ini"
app_server_packages: 
  - uwsgi
  - uwsgi-plugin-python
